jboss-switchyard/tools

eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/operations/CreateSwitchYardProjectOperation.java

creating new SwitchYard projects 
Task-Url: https://issues.jboss.org/browse/SWITCHYARD-2391

SWITCHYARD-2391: Create log4j.xml file in src/test/resources when

---

eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/common/impl/ESBInterfaceControlAdapter.java

fields correctly and clears input, output, fault

SWITCHYARD-2518 - Fixing ESB control adapter so it reacts to empty

---

eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/atom/CamelAtomConsumerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/file/CamelFileConsumerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/file/CamelFileProducerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/ftp/CamelFTPConsumerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/ftp/CamelFTPConsumerMoveAndPollComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/ftp/CamelFTPProducerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/ftps/CamelFTPSConsumerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/ftps/CamelFTPSConsumerMoveAndPollComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/ftps/CamelFTPSProducerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/jpa/CamelJPAConsumerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/jpa/CamelJPAProducerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/mail/CamelMailConsumerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/mail/CamelMailProducerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/rss/CamelRSSConsumerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/sftp/CamelSFTPConsumerComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/sftp/CamelSFTPConsumerMoveAndPollComposite.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/sftp/CamelSFTPProducerComposite.java

SWITCHYARD-2501 - Updates to ensure that connecting objects are in place

---

eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/SwitchYardModelUtils.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/i18n/Messages.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/i18n/messages.properties
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/validation/ServiceWiringConstraints.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/validation/ValidationProblem.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/validation/WiringValidationContext.java

with multi-parameter methods (unsupported)

SWITCHYARD-1888 - Adding additional validation message for interfaces

---

eclipse/plugins/org.switchyard.tools.ui.bpmn2/src/org/switchyard/tools/ui/bpmn2/editor/InputOutputAssociationDetailComposite.java
eclipse/pom.xml

SWITCHYARD-2664 - fixing issue discovered by using the SY TP - missing

---

eclipse/plugins/org.switchyard.tools.ui/plugin.xml
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/facets/SwitchYardRuntimeComponentProvider.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/wizards/ProjectConfigurationWizardPage.java

SWITCHYARD-2499 - toying with plugin.xml to try and get runtime support

---

eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/i18n/Messages.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/i18n/messages.properties
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/validation/InterfaceOpsUtil.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/validation/ServiceWiringConstraints.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/validation/ValidationProblem.java
eclipse/tests/org.switchyard.tools.ui.tests/src/org/switchyard/tools/ui/tests/SwitchYardValidatorTest.java

interface provides more than one operation and the binding does not
specify which to use in the operation selector

SWITCHYARD-1888 - Adding validation for case where Java service

---

eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/mqtt/CamelMQTTProducerComposite.java
eclipse/plugins/org.switchyard.tools.ui/plugin.xml

password fields as well as the missing feature IDs

SWITCHYARD-2718 and SWITCHYARD-2719 - Added missing user name and

---

eclipse/site/pom.xml

add deploy-to-jboss.org profile for publishing via maven deploy; set BUILD_TYPE=snapshots as default publishing path

 add deploy-to-jboss.org profile for publishing via maven deploy; set BUILD_TYPE=snapshots as default publishing path

---

eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/i18n/Messages.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/i18n/messages.properties
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/validation/CamelComponentConstraint.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/validation/ValidationProblem.java
eclipse/tests/org.switchyard.tools.ui.tests/src/org/switchyard/tools/ui/tests/SwitchYardValidatorTest.java

from clauses in the route and adding new tests

SWITCHYARD-2857 - updating Camel route validation to support multiple

---

eclipse/plugins/org.switchyard.tools.ui.bpmn2/META-INF/MANIFEST.MF
eclipse/plugins/org.switchyard.tools.ui.bpmn2/plugin.xml
eclipse/plugins/org.switchyard.tools.ui.bpmn2/src/org/switchyard/tools/ui/bpmn2/editor/SwitchYardCustomTaskPropertiesComposite.java
eclipse/plugins/org.switchyard.tools.ui.bpmn2/src/org/switchyard/tools/ui/bpmn2/editor/SwitchYardServiceTaskPropertiesComposite.java
eclipse/pom.xml

Update bpm tooling to match upstream bpmn2 modeler changes

https://issues.jboss.org/browse/SWITCHYARD-2872

---

eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/wizards/NewSwitchYardProjectWizard.java

the integration and kie versions are not included

SWITCHYARD-2834 - fixing so that if the integration pack isn't selected

---

eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/operations/CreateSwitchYardProjectOperation.java

SWITCHYARD-2871 - fixing issue creating osgi project with no selected

---

eclipse/site/pom.xml
eclipse/site/siteTemplateFolder/index.html

Updated the index.html for the generated site

SWITCHYARD-2921 - updates for site index.html

---

eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/xml/NewCamelXMLRouteCompenentWizard.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/SwitchYardModelUtils.java

the version of SwitchYard (neon)

SWITCHYARD-2947 - updates to generate different camel routes based on

---

eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/transform/JAXBTransformProvider.java

creation. We add the new fields if it's 2.1+ and don't if it's < 2.1

SWITCHYARD-2942 - reacting to runtime version for JAXB transformer

---

eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/transform/JAXBTransformProvider.java

controls if 2.1.x to solve model validation/build issue

SWITCHYARD-2942 - hide JAXB Transformer controls if 2.0.x, show new

---

eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/cxf/CamelCxfProducerComposite.java

SWITCHYARD-2952 - fixes relayHeaders issue for CXF reference bindings

---

eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/diagram/shared/CreateTypeFeature.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/common/impl/SwitchYardProjectWorkingCopy.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/facets/SwitchYardFacetInstallActionDelegate.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/operations/UpdateProjectPomOperation.java

SWITCHYARD-2957 - fixing problem with threading

SWITCHYARD-2907 - fixing facet issue on config version change

---

eclipse/plugins/org.switchyard.tools.ui.bpmn2/plugin.xml
eclipse/plugins/org.switchyard.tools.ui.bpmn2/src/org/switchyard/tools/ui/bpmn2/component/BPMComponentTypeExtension.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/rules/RulesComponentTypeExtension.java
eclipse/plugins/org.switchyard.tools.ui/plugin.xml
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/M2EUtils.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/SwitchYardModelUtils.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/common/impl/SwitchYardProject.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/common/impl/SwitchYardProjectWorkingCopy.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/operations/CreateSwitchYardProjectOperation.java
eclipse/tests/org.switchyard.tools.ui.tests/src/org/switchyard/tools/ui/tests/CreateSwitchYardProjectTest.java
eclipse/tests/org.switchyard.tools.ui.tests/test-data/validation/add_integ_dependency_pom.xml

Fixed some checkstyle issues and test failures

SWITCHYARD-2936 - updates for integration pack groupId support

---

eclipse/plugins/org.switchyard.tools.ui.bpmn2/plugin.xml
eclipse/plugins/org.switchyard.tools.ui.bpmn2/src/org/switchyard/tools/ui/bpmn2/component/BPMComponentTypeExtension.java
eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/rules/RulesComponentTypeExtension.java
eclipse/plugins/org.switchyard.tools.ui/plugin.xml
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/M2EUtils.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/SwitchYardModelUtils.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/common/impl/SwitchYardProject.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/common/impl/SwitchYardProjectWorkingCopy.java
eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/operations/CreateSwitchYardProjectOperation.java
eclipse/tests/org.switchyard.tools.ui.tests/src/org/switchyard/tools/ui/tests/CreateSwitchYardProjectTest.java
eclipse/tests/org.switchyard.tools.ui.tests/test-data/validation/add_integ_dependency_pom.xml

- Migrating all the tweaks from the Mars branch

SWITCHYARD-2936 - hack for intpack

---

pom.xml

Tested locally and both the main SY tools and target platform builds work great.

FUSETOOLS-2268 - updating SY JBTIS version to 4.4.2.Final

---

eclipse/plugins/org.switchyard.tools.ui.editor/src/org/switchyard/tools/ui/editor/components/camel/CamelComponentPaletteEntry.java
eclipse/tests/org.switchyard.tools.ui.tests/META-INF/MANIFEST.MF
pom.xml

This PR will fail to build until the work for https://github.com/jbosstools/jbosstools-fuse/pull/945 has been merged and built upstream. But it's here so we're ready for it when that code is ready.

SWITCHYARD-3014 - update after camel model refactoring

---

pom.xml

Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

SWITCHYARD-3022 - updating to final TP

---

pom.xml

Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

SWITCHYARD-3024 - updating IS TP

---

eclipse/plugins/org.switchyard.tools.ui/src/org/switchyard/tools/ui/i18n/messages.properties

Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

SWITCHYARD-3021 - updating deprecation message for 1.x

---

pom.xml

Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

JBTIS-1185 - upgrading to 4.5.1.Final integration stack TP
